[versions]
sqlDelight = "1.5.4"

koinCore = "3.3.2"
koinAndroid = "3.3.2"
koinAndroidCompose = "3.4.1"
kotlinXDatetime = "0.4.0"

sheetsComposeDialogs = "1.1.1"

appCompat = "1.6.0"
androidCoreKtx = "1.10.0"
androidActivityCompose = "1.6.1"
androidJUnit = "4.13.2"

[libraries]
sqldelight-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }

sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqldelight-coroutineExtensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-androidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-sqliteDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinCore" }
koin-testJUnit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinCore" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidCompose" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinXDatetime" }

sheetsComposeDialogs-core = { module = "com.maxkeppeler.sheets-compose-dialogs:core", version.ref = "sheetsComposeDialogs" }
sheetsComposeDialogs-calendar = { module = "com.maxkeppeler.sheets-compose-dialogs:calendar", version.ref = "sheetsComposeDialogs" }

android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
android-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCoreKtx" }
android-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidActivityCompose" }
android-junit = { module = "junit:junit", version.ref = "androidJUnit" }

[bundles]

[plugins]
#sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }